oracle_parametros:
    host: localhost:1521/orcl
    user: Pruebas
    passwd: Veri1234

oracle_formatos:
    host: localhost:1521/orcl
    user: formato
    passwd: Formatos

oracle_server:
    host: 172.16.32.117:1521/xe
    user: super
    passwd: Veri1234

path:
    dir_target: Files/

headers:
    SP_CONS_CON_NTENSION:
    SP_CONS_CON_ESECTOR:
    SP_CONS_CON_UBICACION:
    SP_CONS_CON_DPTOM:
    SP_CONS_COMPONENTES_TARIFARIOS: CAR_CARG_PERIODO;CAR_CARG_ANO;CAR_T6024_IDEMPRESA;CAR_T6024_CODSUI_MERC;CAR_T6024_METODOLOGIA;CAR_T6024_TIPO_GAS;CAR_T6024_TIPO_USUARIO;CAR_T6024_RANGO;CAR_T6024_PISO_RANGO;CAR_T6024_TECHO_RANGO;CAR_T6024_CUV;CAR_T6024_CUF;CAR_T6024_G;CAR_T6024_CCG;CAR_T6024_V;CAR_T6024_PMS;CAR_T6024_CGLP;CAR_T6024_T;CAR_T6024_CCT;CAR_T6024_CP;CAR_T6024_VT;CAR_T6024_TVM;CAR_T6024_PM;CAR_T6024_DM;CAR_T6024_DUR;CAR_T6024_DUNR;CAR_T6024_D;CAR_T6024_FPC;CAR_T6024_CV;CAR_T6024_CC;CAR_T6024_CF;CAR_T6024_P;CAR_T6024_KCD;CAR_T6024_CONS1;CAR_T6024_CONS2;CAR_T6024_CUEQ1;CAR_T6024_CUEQ2;CAR_T6024_TARIFA1;CAR_T6024_TARIFA2;CAR_T6024_S1;CAR_T6024_S2
    SP_CONS_CARGO_DISTRIBUCION: CAR_CARG_ANO;CAR_CARG_PERIODO;CAR_IDEMPRESA;CAR_T6075_NIE;CAR_T6075_G_COMPRA_COSTO;CAR_T6075_T_TRANSPORTE_COSTO;CAR_T6075_ENTREGA_TIPO;CAR_T6075_CENTRO_POBLADO;CAR_T6075_PRESENTACION_COD;CAR_T6075_CARGO_UNITARIO;CAR_T6075_FLETE;CAR_T6075_TARIFA;CAR_T6075_PUBLICACION_DIARIO;CAR_T6075_PUBLICACION_FECHA
    SP_CONS_CARGO_COMERCIALIZACION: CAR_CARG_ANO;CAR_CARG_PERIODO;CAR_IDEMPRESA;CAR_T6072_NIE;CAR_T6072_COSTO_COMPRA;CAR_T6072_COSTO_TRANSPORTE;CAR_T6072_CENTRO_POBLADO;CAR_T6072_PRESENTACION_COD;CAR_T6072_MEDIO;CAR_T6072_CARGO_UNITARIO_REM;CAR_T6072_CARGO_UNITARIO_CAL;CAR_T6072_FLETE;CAR_T6072_COSTO_UNITARIO;CAR_T6072_DIARIO_COD;CAR_T6072_PUBLICACION_FECHA
    SP_CONS_CONSULTA_PDF: ID_EMPRESA;NOMBRE_EMPRESA;ID_FORMATO;NOMBRE_FORMATO;ESTADO_FORMATO;NOMBRE_ARCHIVO;ANNO;CAR_CARG_PERIODO;URL_DONDE_SE_ENCUENTRA_EL_PDF
    SP_CONS_INFO_TECN_CILINDROS_MARCADOS: CAR_CARG_ANO;CAR_CARG_PERIODO,IDENTIFICADOR_EMPRESA;CAR_T6009_AGNO_FAB;CAR_T6009_CODIG_FABRIC;CAR_T6009_CONS_FABRIC;CAR_T6009_CODIG_TECN_FABRIC;CAR_T6009_CAPC_CILIND_NUMERIC;CAR_T6009_CODIG_MARCA;CAR_T6009_CODIG_TRAB_EJEC;CAR_T6009_FECHA_EJEC_TRAB;CAR_T6009_NUM_CERTF_CONF
    SP_CONS_VENTAS_DISTRIBUCION: CAR_CARG_PERIODO;CAR_CARG_ANO;IDENTIFICADOR_EMPRESA;CAR_T6076_SECUE;CAR_T6076_NIE;CAR_T6076_TIP_ENTREGA;CAR_T6076_COD_PRESENTACION;CAR_T6076_CIT_NIF;CAR_T6076_MARCA;CAR_T6076_IDENTIFICACION;CAR_T6076_CENTRO_POBLADO;CAR_T6076_SECTOR;CAR_T6076_ZONA;CAR_T6076_NUMERO_FACTURA;CAR_T6076_VALOR_FACTURA;CAR_T6076_CANTIDAD
    SP_CONS_VENTAS_CILINDROS: CAR_CARG_PERIODO;CAR_CARG_ANO;CAR_CARG_SECUE;CAR_IDEMPRESA;CAR_T6073_NIE;CAR_T6073_NIF;CAR_T6073_CENTRO_POBLADO;CAR_T6073_SECTOR;CAR_T6073_ZONA;CAR_T6073_MEDIO;CAR_T6073_COD_PRESENTACION;CAR_T6073_FACT_NRO;CAR_T6073_FACT_VALOR;CAR_T6073_CANTIDAD;CAR_T6073_SUBSIDIO;CAR_T6073_CANTIDAD_KG
    SP_CONS_CON_PAT_CROM: FECHA_INICIO;FECHA_FINAL;COD_CONCEPTO;VALOR;ID_EMPRESA;ARE_ESP_NOMBRE;NUM_RADICADO;ANO_REPOR
            
